name: 'pycovcheck'
description: 'Asserts test coverage thresholds from a python coverage xml file'
inputs:
  packages:
    description: 'set of package:treshold statements, where treshold is a percentage expressed as float'
    required: true
    default: ''
  classes:  
    description: 'set of class:treshold statements, where treshold is a percentage expressed as float'
    required: true
    default: ''
  coveragefile:  
    description: 'path to the python coverage xml file'
    required: true
    default: './coverage.xml'
branding:
  icon: 'check-circle'
  color: 'orange'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - coveragefile=${{ inputs.coveragefile }}
    - packages=${{ inputs.packages }}
    - classes=${{ inputs.classes }}