name: Integration Tests

on:
  workflow_call:
  workflow_dispatch:
 
permissions:
  contents: read

jobs:
  
  classes:
    uses: ./.github/workflows/it-coverage-classes.yml

  packages:
    uses: ./.github/workflows/it-coverage-packages.yml
    

  
